# Server configuration
server:
  port: 8080
  read_timeout_seconds: 15
  write_timeout_seconds: 15
  idle_timeout_seconds: 60

# Database configuration
database:
  url: "postgres://postgres:postgres@localhost:5432/postgres"
  max_connections: 10
  min_connections: 1
  max_connection_lifetime_hours: 1
  max_connection_idle_minutes: 30

# Logging configuration
logging:
  level: "info"  # debug, info, error
  format: "text" # text or json

# Version information
meta:
  version: "1.0.0"
  build_date: "2025-03-22"
  author: "NieRVoid"